deployment:
  # imageversion: IMAGE_VERSION
  imageversion: 1.1
  image: 180294178330.dkr.ecr.us-east-1.amazonaws.com/expense/dev/frontend
service:
  port: 80
hpa:
  CPU: 70
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:180294178330:targetgroup/frontend/c55a3d95d168a748